CREATE USER 'ï»pofr_'@'localhost' IDENTIFIED BY usuario;
CREATE DATABASE bdï»pofr_;
GRANT ALL PRIVILEGES ON bdï»pofr_.* TO 'ï»pofr_'@'localhost' IDENTIFIED BY  usuario;
CREATE USER 'culoju_'@'localhost' IDENTIFIED BY usuario;
CREATE DATABASE bdculoju_;
GRANT ALL PRIVILEGES ON bdculoju_.* TO 'culoju_'@'localhost' IDENTIFIED BY  usuario;
CREATE USER 'ducapa_'@'localhost' IDENTIFIED BY usuario;
CREATE DATABASE bdducapa_;
GRANT ALL PRIVILEGES ON bdducapa_.* TO 'ducapa_'@'localhost' IDENTIFIED BY  usuario;
CREATE USER 'gafoem_'@'localhost' IDENTIFIED BY usuario;
CREATE DATABASE bdgafoem_;
GRANT ALL PRIVILEGES ON bdgafoem_.* TO 'gafoem_'@'localhost' IDENTIFIED BY  usuario;
CREATE USER 'gumofr_'@'localhost' IDENTIFIED BY usuario;
CREATE DATABASE bdgumofr_;
GRANT ALL PRIVILEGES ON bdgumofr_.* TO 'gumofr_'@'localhost' IDENTIFIED BY  usuario;
CREATE USER 'jihian_'@'localhost' IDENTIFIED BY usuario;
CREATE DATABASE bdjihian_;
GRANT ALL PRIVILEGES ON bdjihian_.* TO 'jihian_'@'localhost' IDENTIFIED BY  usuario;
CREATE USER 'logoje_'@'localhost' IDENTIFIED BY usuario;
CREATE DATABASE bdlogoje_;
GRANT ALL PRIVILEGES ON bdlogoje_.* TO 'logoje_'@'localhost' IDENTIFIED BY  usuario;
CREATE USER 'lotoda_'@'localhost' IDENTIFIED BY usuario;
CREATE DATABASE bdlotoda_;
GRANT ALL PRIVILEGES ON bdlotoda_.* TO 'lotoda_'@'localhost' IDENTIFIED BY  usuario;
CREATE USER 'lupaul_'@'localhost' IDENTIFIED BY usuario;
CREATE DATABASE bdlupaul_;
GRANT ALL PRIVILEGES ON bdlupaul_.* TO 'lupaul_'@'localhost' IDENTIFIED BY  usuario;
CREATE USER 'masoja_'@'localhost' IDENTIFIED BY usuario;
CREATE DATABASE bdmasoja_;
GRANT ALL PRIVILEGES ON bdmasoja_.* TO 'masoja_'@'localhost' IDENTIFIED BY  usuario;
CREATE USER 'miibra_'@'localhost' IDENTIFIED BY usuario;
CREATE DATABASE bdmiibra_;
GRANT ALL PRIVILEGES ON bdmiibra_.* TO 'miibra_'@'localhost' IDENTIFIED BY  usuario;
CREATE USER 'mopora_'@'localhost' IDENTIFIED BY usuario;
CREATE DATABASE bdmopora_;
GRANT ALL PRIVILEGES ON bdmopora_.* TO 'mopora_'@'localhost' IDENTIFIED BY  usuario;
CREATE USER 'mucoes_'@'localhost' IDENTIFIED BY usuario;
CREATE DATABASE bdmucoes_;
GRANT ALL PRIVILEGES ON bdmucoes_.* TO 'mucoes_'@'localhost' IDENTIFIED BY  usuario;
CREATE USER 'naprra_'@'localhost' IDENTIFIED BY usuario;
CREATE DATABASE bdnaprra_;
GRANT ALL PRIVILEGES ON bdnaprra_.* TO 'naprra_'@'localhost' IDENTIFIED BY  usuario;
CREATE USER 'nazuel_'@'localhost' IDENTIFIED BY usuario;
CREATE DATABASE bdnazuel_;
GRANT ALL PRIVILEGES ON bdnazuel_.* TO 'nazuel_'@'localhost' IDENTIFIED BY  usuario;
CREATE USER 'pegoda_'@'localhost' IDENTIFIED BY usuario;
CREATE DATABASE bdpegoda_;
GRANT ALL PRIVILEGES ON bdpegoda_.* TO 'pegoda_'@'localhost' IDENTIFIED BY  usuario;
CREATE USER 'rarupe_'@'localhost' IDENTIFIED BY usuario;
CREATE DATABASE bdrarupe_;
GRANT ALL PRIVILEGES ON bdrarupe_.* TO 'rarupe_'@'localhost' IDENTIFIED BY  usuario;
CREATE USER 'romoju_'@'localhost' IDENTIFIED BY usuario;
CREATE DATABASE bdromoju_;
GRANT ALL PRIVILEGES ON bdromoju_.* TO 'romoju_'@'localhost' IDENTIFIED BY  usuario;
CREATE USER 'rugama_'@'localhost' IDENTIFIED BY usuario;
CREATE DATABASE bdrugama_;
GRANT ALL PRIVILEGES ON bdrugama_.* TO 'rugama_'@'localhost' IDENTIFIED BY  usuario;
CREATE USER 'sasapa_'@'localhost' IDENTIFIED BY usuario;
CREATE DATABASE bdsasapa_;
GRANT ALL PRIVILEGES ON bdsasapa_.* TO 'sasapa_'@'localhost' IDENTIFIED BY  usuario;
